### ISSUE TITLE
Non-underhanded example submission

### ISSUE THREAD

**Issue by erickt** [rust-community/underhanded.rs#9]
From [HN](https://news.ycombinator.com/item?id=13186980):

> Suggestion: could you provide an example submission, which is ideal for what you're looking for except for not being underhanded?
> 
> Benefits:
> 
> - More approachable to mess around with for newbies -- download the example and try to break it.
> 
> - More likely that you'll get submissions from experts who have time to implement the underhanded part but may not get around to putting together the boilerplate.
> 
> - More likely that submissions will get the general task right and look similar for parts that don't matter, making for easier review.
> 
> Drawbacks:
> 
> - Potential for too many cookie cutter submissions.
> 
> - Might lead people away from thinking about alternate server designs that are more underhanded.
> 
> Mostly I think this might be worth doing because of the second benefit -- you're asking people to do a bunch of grunt work even after they've figured out the core underhanded technique.

**Comment by gmorenz** [comment]
Another drawback is that spotting potential sources of underhandedness becomes a lot easier because you just have to look for the changes.

**Comment by erickt** [comment]
@gmorenz: We'll try to take account for this as part of our judging. We'll try to view each submission as if we're doing a normal code review, so if a lot of people start from a similar base that shouldn't hurt their chances. Creativity will end up counting more if we end up getting a lot of submissions for the same style of attack.

**Comment by erickt** [comment]
Implemented [here](http://github.com/erickt/quad-bank).
